import type { Episode, Podcast } from './types'
import { formatDuration, longDate } from './format'
import { cover, docFooter, downloadWord, esc, inline, leadParagraph, sanitizeFilename, section, wordShell } from './exportDoc'

// Builds the institution-grade single-episode Word document: a navy cover, then
// AI Summary (lead) · Ideas Pitched · Highlights · Q&A.

export function summaryToWord(episode: Episode, podcast?: Podcast, logo?: string): string {
  const s = episode.summary

  const synthesis = s?.synthesis ?? []
  const summaryBody = synthesis.length
    ? `<div class="lead">${synthesis
        .map((p, i) => `<p${i === synthesis.length - 1 ? ' class="last"' : ''}>${i === 0 ? leadParagraph(p) : inline(p)}</p>`)
        .join('')}</div>`
    : ''

  // Concrete ideas pitched — the call, who made it, gold-diamond thesis bullets.
  const ideas = s?.ideas ?? []
  const ideasBody = ideas.length
    ? ideas
        .map((idea) => {
          const kind = idea.kind ? `<span class="idea-kind">${esc(idea.kind)}</span>` : ''
          const who = idea.proponent && idea.proponent !== '—' ? `<p class="idea-who">Pitched by <b>${esc(idea.proponent)}</b></p>` : ''
          const thesis = idea.thesis.length
            ? `<ul class="thesis">${idea.thesis.map((t) => `<li><span class="di">&#9670;</span>${inline(t)}</li>`).join('')}</ul>`
            : ''
          return `<div class="idea"><div class="idea-title">${kind}${esc(idea.idea)}</div>${who}${thesis}</div>`
        })
        .join('')
    : ''

  // Timeline order, with the AI's key takeaways starred.
  const highlightsBody = s?.highlights.length
    ? s.highlights
        .map(
          (h) =>
            `<div class="moment"><p class="m-title"><span class="ts">${esc(h.timestamp)}</span>${
              h.key ? '<span class="m-star">&#9733;</span> ' : ''
            }${esc(h.title)}</p><p class="m-why">${inline(h.detail)}</p></div>`,
        )
        .join('')
    : ''

  const qaBody = s?.qa.length
    ? s.qa
        .map(
          (item) =>
            `<div class="qa-item"><p class="qa-q"><span class="qb">Q</span>${esc(item.q)}</p><p class="qa-a">${inline(item.a)}</p></div>`,
        )
        .join('')
    : ''

  const inner = `${cover({
    eyebrow: podcast ? `${podcast.title} · ${podcast.author}` : 'Episode Intelligence',
    kicker: 'Episode Intelligence',
    title: episode.title,
    dateRange: longDate(episode.publishedAt),
    chips: [formatDuration(episode.durationSec), ...(s ? [`${s.highlights.length} highlights`, `${s.qa.length} questions`] : [])],
    logo,
    footerLeft: 'Generated by <b>Munshot</b> &middot; AI podcast intelligence',
  })}
      ${section('01', 'AI Summary', summaryBody)}
      ${section('02', 'Ideas Pitched', ideasBody)}
      ${section('03', 'Highlights', highlightsBody)}
      ${section('04', 'Q&A', qaBody)}
      ${docFooter('Generated by <b>Munshot</b> &middot; AI podcast intelligence', longDate(episode.publishedAt))}`

  return wordShell(`${episode.title} — Munshot Summary`, inner)
}

// Build the document and download it directly as a Word (.doc) file.
export async function downloadSummary(episode: Episode, podcast?: Podcast): Promise<void> {
  const { MUNSHOT_LOGO } = await import('./brandLogo')
  const name = sanitizeFilename(`${podcast ? `${podcast.title} — ` : ''}${episode.title} — Munshot`)
  downloadWord(`${name}.doc`, summaryToWord(episode, podcast, MUNSHOT_LOGO))
}
