import type { Episode, Podcast, WeeklyIdea, WeeklyShowDigest, WeeklySummary } from './types'
import { brandHeader, chips, docFooter, downloadWord, esc, inline, sanitizeFilename, section, wordShell } from './exportDoc'

// Builds a clean, well-formatted Weekly Summary Word document. The primary body is
// organized BY SHOW (each show's pitched ideas · key takeaways · questions), with
// cross-show Themes, Mentions, and the curated "interesting" moment after it, plus
// source-episode citations.

type ById<T> = (id: string) => T | undefined

// One pitched idea: the call (with an optional category badge), who pitched it, and
// the thesis bullets behind it.
function ideaBlock(idea: WeeklyIdea): string {
  const kind = idea.kind ? `<span class="idea-kind">${esc(idea.kind)}</span>` : ''
  const who = idea.proponent && idea.proponent !== '—' ? `<p class="idea-who">Pitched by ${esc(idea.proponent)}</p>` : ''
  const thesis = idea.thesis.length ? `<ul class="thesis">${idea.thesis.map((t) => `<li>${inline(t)}</li>`).join('')}</ul>` : ''
  return `<div class="idea"><p class="idea-title">${kind}${esc(idea.idea)}</p>${who}${thesis}</div>`
}

// One show's mini-digest: ideas pitched, then key takeaways, then open questions.
function showBlock(d: WeeklyShowDigest): string {
  const count = `${d.episodeCount} episode${d.episodeCount === 1 ? '' : 's'}`
  const ideas = d.ideas.length ? `<p class="subhead">Ideas Pitched</p>${d.ideas.map(ideaBlock).join('')}` : ''
  const takeaways = d.takeaways.length
    ? `<p class="subhead">Key Takeaways</p><ul class="tlist">${d.takeaways
        .map((t) => `<li><b>${esc(t.title)}.</b> ${inline(t.detail)}</li>`)
        .join('')}</ul>`
    : ''
  const questions = d.questions.length
    ? `<p class="subhead">Questions</p><ul class="tlist">${d.questions.map((q) => `<li>${inline(q)}</li>`).join('')}</ul>`
    : ''
  return `<div class="show-block"><p class="show-head">${esc(d.show)} <span class="show-count">${esc(count)}</span></p>${ideas}${takeaways}${questions}</div>`
}

export function weeklyToWord(weekly: WeeklySummary, episodeById: ById<Episode>, podcastById: ById<Podcast>): string {
  const meta = [weekly.rangeLabel, `${weekly.episodeCount} episodes`, `${weekly.readMinutes} min read`]
    .map((m) => `<span>${esc(m)}</span>`)
    .join('<i class="dot">&middot;</i>')

  const overview = weekly.overview.length
    ? `<div class="prose">${weekly.overview.map((p) => `<p>${inline(p)}</p>`).join('')}</div>`
    : ''

  const showsBody = (weekly.shows ?? []).map(showBlock).join('')

  const themes = chips(weekly.topThemes.map((t) => t.label))

  const interestingTitle = weekly.interesting.title ? `<p class="qt">${esc(weekly.interesting.title)}</p>` : ''
  const interesting = weekly.interesting.quote
    ? `<div class="quote">${interestingTitle}<p class="ql">${esc(weekly.interesting.quote)}</p><p class="who">${esc(
        weekly.interesting.speaker,
      )} <span class="role">${esc(weekly.interesting.role)}</span></p></div>`
    : ''

  const contradictions = weekly.contradictions.length
    ? weekly.contradictions.map((c) => `<p class="callout">${inline(c)}</p>`).join('')
    : ''

  const mentions = `<table class="cols" role="presentation" cellpadding="0" cellspacing="0"><tr>
      <td><p class="subhead">People</p>${chips(weekly.mentions.people)}</td>
      <td><p class="subhead">Companies</p>${chips(weekly.mentions.companies)}</td>
    </tr></table>`

  const sources = weekly.sourceEpisodeIds.map(episodeById).filter((e): e is Episode => Boolean(e))
  const sourcesBody = sources.length
    ? `<table class="srcs" role="presentation" cellpadding="0" cellspacing="0">${sources
        .map(
          (ep) =>
            `<tr><td>${esc(ep.title)}</td><td class="src-show">${esc(podcastById(ep.podcastId)?.title ?? '')}</td></tr>`,
        )
        .join('')}</table>`
    : ''

  const inner = `${brandHeader('Weekly Intelligence')}
      <h1>Weekly Summary</h1>
      <p class="meta">${meta}</p>
      <hr class="rule" />
      ${section('01', 'This Week in Summary', overview)}
      ${section('02', 'By Show', showsBody)}
      ${section('03', 'Top Themes', themes)}
      ${section('04', 'Mentions', mentions)}
      ${section('05', 'What Was Actually Interesting', interesting)}
      ${section('06', 'Contradictions & Disagreements', contradictions)}
      ${section('07', 'Source Episodes', sourcesBody)}
      ${docFooter('Generated by <b>Munshot</b> &middot; AI podcast intelligence', weekly.rangeLabel)}`

  return wordShell(`Munshot Weekly — ${weekly.rangeLabel}`, inner)
}

export function downloadWeekly(weekly: WeeklySummary, episodeById: ById<Episode>, podcastById: ById<Podcast>): void {
  downloadWord(`Munshot Weekly — ${sanitizeFilename(weekly.rangeLabel)}.doc`, weeklyToWord(weekly, episodeById, podcastById))
}
