import type { Episode, Podcast } from './types'
import { formatDuration, longDate } from './format'
import { brandHeader, docShell, downloadDoc, esc, inline, sanitizeFilename, section } from './exportDoc'

// Builds the standalone, print-ready document for a single episode's AI summary
// (AI Summary · Key Takeaways · Q&A · Interesting Moments) and downloads it.

export function summaryToHtml(episode: Episode, podcast?: Podcast): string {
  const s = episode.summary
  const meta = [
    longDate(episode.publishedAt),
    formatDuration(episode.durationSec),
    s ? `${s.takeaways.length} takeaways` : '',
    s ? `${s.moments.length} moments` : '',
  ]
    .filter(Boolean)
    .map((m) => `<span>${esc(m)}</span>`)
    .join('<i class="dot">·</i>')

  const summaryBody = s?.synthesis.length
    ? `<div class="prose">${s.synthesis.map((p) => `<p>${inline(p)}</p>`).join('')}</div>`
    : ''

  const takeawaysBody = s?.takeaways.length
    ? `<ol class="takeaways">${s.takeaways
        .map((t) => `<li><p class="t-title">${esc(t.title)}</p><p class="t-detail">${esc(t.detail)}</p></li>`)
        .join('')}</ol>`
    : ''

  const qaBody = s?.qa.length
    ? `<div class="qa">${s.qa
        .map(
          (item) =>
            `<div class="qa-item"><p class="q"><span class="q-badge">Q</span>${esc(item.q)}</p><p class="a">${esc(item.a)}</p></div>`,
        )
        .join('')}</div>`
    : ''

  const momentsBody = s?.moments.length
    ? `<div class="moments">${s.moments
        .map(
          (m) =>
            `<div class="moment"><div class="m-head"><span class="ts">${esc(m.timestamp)}</span><p class="m-title">${esc(m.title)}</p></div><p class="m-why">${esc(m.whyItMatters)}</p></div>`,
        )
        .join('')}</div>`
    : ''

  const show = podcast ? `${esc(podcast.title)} · ${esc(podcast.author)}` : ''

  const inner = `${brandHeader('Episode Intelligence')}
      ${show ? `<p class="show">${show}</p>` : ''}
      <h1>${esc(episode.title)}</h1>
      <p class="meta">${meta}</p>
      <hr class="rule" />
      ${section('01', 'AI Summary', summaryBody)}
      ${section('02', 'Key Takeaways', takeawaysBody)}
      ${section('03', 'Q&A', qaBody)}
      ${section('04', 'Interesting Moments', momentsBody)}
      <footer>
        <span>Generated by <b>Munshot</b> · AI podcast intelligence</span>
        <span>${esc(longDate(episode.publishedAt))}</span>
      </footer>`

  return docShell(`${episode.title} — Munshot Summary`, inner)
}

// Build the document and hand it to the user as a downloaded .html file.
export function downloadSummary(episode: Episode, podcast?: Podcast): void {
  const name = sanitizeFilename(`${podcast ? `${podcast.title} — ` : ''}${episode.title}`)
  downloadDoc(`${name}.html`, summaryToHtml(episode, podcast))
}
