import type { Episode, Podcast, WeeklySummary } from './types'
import { brandHeader, chips, docFooter, downloadWord, esc, inline, sanitizeFilename, section, wordShell } from './exportDoc'

// Builds a clean, well-formatted Weekly Summary Word document — every section the
// page shows (Overview · Top Themes · Key Takeaways · Interesting Ideas ·
// Contradictions · Mentions · Questions) plus source-episode citations.

type ById<T> = (id: string) => T | undefined

export function weeklyToWord(weekly: WeeklySummary, episodeById: ById<Episode>, podcastById: ById<Podcast>): string {
  const meta = [weekly.rangeLabel, `${weekly.episodeCount} episodes`, `${weekly.readMinutes} min read`]
    .map((m) => `<span>${esc(m)}</span>`)
    .join('<i class="dot">&middot;</i>')

  const overview = weekly.overview.length
    ? `<div class="prose">${weekly.overview.map((p) => `<p>${inline(p)}</p>`).join('')}</div>`
    : ''

  const themes = chips(weekly.topThemes.map((t) => t.label))

  const takeaways = weekly.takeaways.length
    ? weekly.takeaways
        .map(
          (t, i) =>
            `<div class="tk"><p class="t-title"><span class="t-num">${String(i + 1).padStart(2, '0')}</span>&nbsp;&nbsp;${esc(
              t.title,
            )}</p><p class="t-detail">${inline(t.detail)}</p></div>`,
        )
        .join('')
    : ''

  const interestingTitle = weekly.interesting.title ? `<p class="qt">${esc(weekly.interesting.title)}</p>` : ''
  const interesting = `<div class="quote">${interestingTitle}<p class="ql">${esc(weekly.interesting.quote)}</p><p class="who">${esc(
    weekly.interesting.speaker,
  )} <span class="role">${esc(weekly.interesting.role)}</span></p></div>`

  const contradictions = weekly.contradictions.length
    ? weekly.contradictions.map((c) => `<p class="callout">${inline(c)}</p>`).join('')
    : ''

  const mentions = `<table class="cols" role="presentation" cellpadding="0" cellspacing="0"><tr>
      <td><p class="subhead">People</p>${chips(weekly.mentions.people)}</td>
      <td><p class="subhead">Companies</p>${chips(weekly.mentions.companies)}</td>
    </tr></table>`

  const questions = weekly.questions.length
    ? weekly.questions.map((q) => `<p class="callout">${inline(q)}</p>`).join('')
    : ''

  const sources = weekly.sourceEpisodeIds.map(episodeById).filter((e): e is Episode => Boolean(e))
  const sourcesBody = sources.length
    ? `<table class="srcs" role="presentation" cellpadding="0" cellspacing="0">${sources
        .map(
          (ep) =>
            `<tr><td>${esc(ep.title)}</td><td class="src-show">${esc(podcastById(ep.podcastId)?.title ?? '')}</td></tr>`,
        )
        .join('')}</table>`
    : ''

  const inner = `${brandHeader('Weekly Intelligence')}
      <h1>Weekly Summary</h1>
      <p class="meta">${meta}</p>
      <hr class="rule" />
      ${section('01', 'This Week in Summary', overview)}
      ${section('02', 'Top Themes', themes)}
      ${section('03', 'Key Takeaways', takeaways)}
      ${section('04', 'What Was Actually Interesting', interesting)}
      ${section('05', 'Contradictions & Disagreements', contradictions)}
      ${section('06', 'Mentions', mentions)}
      ${section('07', 'Questions Worth Investigating', questions)}
      ${section('08', 'Source Episodes', sourcesBody)}
      ${docFooter('Generated by <b>Munshot</b> &middot; AI podcast intelligence', weekly.rangeLabel)}`

  return wordShell(`Munshot Weekly — ${weekly.rangeLabel}`, inner)
}

export function downloadWeekly(weekly: WeeklySummary, episodeById: ById<Episode>, podcastById: ById<Podcast>): void {
  downloadWord(`Munshot Weekly — ${sanitizeFilename(weekly.rangeLabel)}.doc`, weeklyToWord(weekly, episodeById, podcastById))
}
