import type { Episode, Podcast } from './types'
import { formatDuration, longDate } from './format'
import { brandHeader, docFooter, downloadWord, esc, inline, sanitizeFilename, section, wordShell } from './exportDoc'

// Builds a clean, well-formatted Word document for a single episode's AI summary
// (AI Summary · Highlights · Q&A) and downloads it.

export function summaryToWord(episode: Episode, podcast?: Podcast): string {
  const s = episode.summary
  const meta = [
    longDate(episode.publishedAt),
    formatDuration(episode.durationSec),
    s ? `${s.highlights.length} highlights` : '',
    s ? `${s.qa.length} questions` : '',
  ]
    .filter(Boolean)
    .map((m) => `<span>${esc(m)}</span>`)
    .join('<i class="dot">&middot;</i>')

  const summaryBody = s?.synthesis.length
    ? `<div class="prose">${s.synthesis.map((p) => `<p>${inline(p)}</p>`).join('')}</div>`
    : ''

  // Concrete ideas pitched — the call, who made it, and the thesis behind each.
  const ideas = s?.ideas ?? []
  const ideasBody = ideas.length
    ? ideas
        .map((idea) => {
          const kind = idea.kind ? `<span class="idea-kind">${esc(idea.kind)}</span>` : ''
          const who = idea.proponent && idea.proponent !== '—' ? `<p class="idea-who">Pitched by ${esc(idea.proponent)}</p>` : ''
          const thesis = idea.thesis.length ? `<ul class="thesis">${idea.thesis.map((t) => `<li>${inline(t)}</li>`).join('')}</ul>` : ''
          return `<div class="idea"><p class="idea-title">${kind}${esc(idea.idea)}</p>${who}${thesis}</div>`
        })
        .join('')
    : ''

  // Timeline order, with the AI's key takeaways starred.
  const highlightsBody = s?.highlights.length
    ? s.highlights
        .map(
          (h) =>
            `<div class="moment"><p class="m-title"><span class="ts">${esc(h.timestamp)}</span>&nbsp;&nbsp;${
              h.key ? '&#9733;&nbsp;' : ''
            }${esc(h.title)}</p><p class="m-why">${inline(h.detail)}</p></div>`,
        )
        .join('')
    : ''

  const qaBody = s?.qa.length
    ? s.qa
        .map(
          (item) =>
            `<div class="qa-item"><p class="q"><span class="qb">Q</span>&nbsp;&nbsp;${esc(
              item.q,
            )}</p><p class="a">${inline(item.a)}</p></div>`,
        )
        .join('')
    : ''

  const show = podcast ? `${esc(podcast.title)} &middot; ${esc(podcast.author)}` : ''

  const inner = `${brandHeader('Episode Intelligence')}
      ${show ? `<p class="show">${show}</p>` : ''}
      <h1>${esc(episode.title)}</h1>
      <p class="meta">${meta}</p>
      <hr class="rule" />
      ${section('01', 'AI Summary', summaryBody)}
      ${section('02', 'Ideas Pitched', ideasBody)}
      ${section('03', 'Highlights', highlightsBody)}
      ${section('04', 'Q&A', qaBody)}
      ${docFooter('Generated by <b>Munshot</b> &middot; AI podcast intelligence', longDate(episode.publishedAt))}`

  return wordShell(`${episode.title} — Munshot Summary`, inner)
}

// Build the document and download it directly as a Word (.doc) file.
export function downloadSummary(episode: Episode, podcast?: Podcast): void {
  const name = sanitizeFilename(`${podcast ? `${podcast.title} — ` : ''}${episode.title} — Munshot`)
  downloadWord(`${name}.doc`, summaryToWord(episode, podcast))
}
