import type { Episode, Podcast, WeeklySummary } from './types'
import { brandHeader, chips, docShell, downloadDoc, esc, printDoc, sanitizeFilename, section } from './exportDoc'

// Builds the standalone, print-ready Weekly Summary document — every section the
// page shows (Overview · Top Themes · Key Takeaways · Interesting Ideas ·
// Contradictions · Mentions · Questions) plus the source-episode citations.

type ById<T> = (id: string) => T | undefined

export function weeklyToHtml(weekly: WeeklySummary, episodeById: ById<Episode>, podcastById: ById<Podcast>): string {
  const meta = [weekly.rangeLabel, `${weekly.episodeCount} episodes`, `${weekly.readMinutes} min read`]
    .map((m) => `<span>${esc(m)}</span>`)
    .join('<i class="dot">·</i>')

  const overview = weekly.overview.length
    ? `<div class="prose">${weekly.overview.map((p) => `<p>${esc(p)}</p>`).join('')}</div>`
    : ''

  const themes = chips(weekly.topThemes.map((t) => t.label))

  const takeaways = weekly.takeaways.length
    ? `<ol class="takeaways">${weekly.takeaways
        .map((t) => `<li><p class="t-title">${esc(t.title)}</p><p class="t-detail">${esc(t.detail)}</p></li>`)
        .join('')}</ol>`
    : ''

  const interesting = `<div class="quote"><p>&ldquo;${esc(weekly.interesting.quote)}&rdquo;</p><span class="who">${esc(weekly.interesting.speaker)}</span><span class="role">${esc(weekly.interesting.role)}</span></div>`

  const contradictions = weekly.contradictions.length
    ? weekly.contradictions.map((c) => `<div class="callout">${esc(c)}</div>`).join('')
    : ''

  const mentions = `<div class="cols"><div><p class="subhead">People</p>${chips(weekly.mentions.people)}</div><div><p class="subhead">Companies</p>${chips(weekly.mentions.companies)}</div></div>`

  const questions = weekly.questions.length
    ? weekly.questions.map((q) => `<div class="callout">${esc(q)}</div>`).join('')
    : ''

  const sources = weekly.sourceEpisodeIds.map(episodeById).filter((e): e is Episode => Boolean(e))
  const sourcesBody = sources.length
    ? `<ul class="srcs">${sources
        .map((ep) => `<li><span>${esc(ep.title)}</span><span class="src-show">${esc(podcastById(ep.podcastId)?.title ?? '')}</span></li>`)
        .join('')}</ul>`
    : ''

  const inner = `${brandHeader('Weekly Intelligence')}
      <h1>Weekly Summary</h1>
      <p class="meta">${meta}</p>
      <hr class="rule" />
      ${section('01', 'This Week in Summary', overview)}
      ${section('02', 'Top Themes', themes)}
      ${section('03', 'Key Takeaways', takeaways)}
      ${section('04', 'What Was Actually Interesting', interesting)}
      ${section('05', 'Contradictions & Disagreements', contradictions)}
      ${section('06', 'Mentions', mentions)}
      ${section('07', 'Questions Worth Investigating', questions)}
      ${section('08', 'Source Episodes', sourcesBody)}
      <footer>
        <span>Generated by <b>Munshot</b> · AI podcast intelligence</span>
        <span>${esc(weekly.rangeLabel)}</span>
      </footer>`

  return docShell(`Munshot Weekly — ${weekly.rangeLabel}`, inner)
}

export function downloadWeekly(weekly: WeeklySummary, episodeById: ById<Episode>, podcastById: ById<Podcast>): void {
  downloadDoc(`Munshot Weekly — ${sanitizeFilename(weekly.rangeLabel)}.html`, weeklyToHtml(weekly, episodeById, podcastById))
}

export function printWeekly(weekly: WeeklySummary, episodeById: ById<Episode>, podcastById: ById<Podcast>): void {
  printDoc(weeklyToHtml(weekly, episodeById, podcastById))
}
