import type { jsPDF as JsPdf } from 'jspdf'
import type { Episode, Idea, Podcast, WeeklyIdea, WeeklySummary } from './types'
import { formatDuration, longDate } from './format'
import { sanitizeFilename } from './exportDoc'
import { episodeSourceUrl } from './source'

// ─────────────────────────────────────────────────────────────────────────────
// PDF export — a REAL .pdf, generated by a library (jsPDF), downloaded as a Blob.
//
// Why not the browser's print → Save-as-PDF? Because the app runs inside the
// chat.muns.io dashboard iframe, sandboxed WITHOUT `allow-modals`, so any
// script-initiated window.print() is a silent no-op. So we build the document
// ourselves — exactly like the Word `.doc` export does — and hand the user a
// finished file via `allow-downloads` (which always works in that sandbox).
//
// The whole house style is drawn as vector: the dark gradient cover (painted to
// an offscreen canvas, embedded as the cover image), gold section rules, the
// drop-cap lead, diamond-bullet idea cards, the dark quote panel, and the zebra
// source table. Text is real, selectable text. Fonts follow the same serif/sans/
// mono split the .doc uses (Times / Helvetica / Courier ≈ Georgia / Calibri /
// Consolas) — the three standard PDF families, so nothing needs embedding.
//
// Colours: navy #1a2b4a · gold #b8902f. **bold** spans render gold, like the app.
// ─────────────────────────────────────────────────────────────────────────────

type RGB = [number, number, number]
type ById<T> = (id: string) => T | undefined

const A4 = { w: 595.28, h: 841.89 } // points
const M = { l: 46, r: 46, t: 46, b: 48 }
const CW = A4.w - M.l - M.r

const C: Record<string, RGB> = {
  navy: [26, 43, 74],
  ink: [10, 19, 34],
  ink2: [43, 56, 80], // lead body #2b3850
  body: [65, 80, 106], // #41506a
  gold: [184, 144, 47],
  goldB: [206, 163, 68],
  goldDim: [150, 121, 52], // dim gold for hairline borders on light
  goldPale: [231, 207, 147],
  goldTint: [250, 246, 234],
  slate: [84, 96, 110],
  panel: [246, 248, 251],
  panel2: [238, 242, 247],
  line: [230, 234, 241],
  line2: [212, 219, 230],
  white: [255, 255, 255],
  zebra: [250, 251, 253],
  quoteBg: [19, 34, 58],
  coverTitle: [244, 238, 223],
  coverBrand: [243, 246, 251],
  coverFoot: [159, 176, 198],
}

const KIND_LABEL: Record<NonNullable<Idea['kind']>, string> = {
  stock: 'Stock',
  trade: 'Trade',
  macro: 'Macro',
  prediction: 'Prediction',
}

// ── Content model (pure, testable) ───────────────────────────────────────────
// Each block maps to one renderer. Sections are emitted only when they have a
// body (mirrors the .doc, which drops empty sections).
type Token = { w: string; b: boolean; c?: RGB }

export type Block =
  | { k: 'cover'; eyebrow?: string; kicker: string; title: string; dateRange?: string; chips: string[]; footerLeft: string }
  | { k: 'section'; num: string; title: string }
  | { k: 'lead'; paras: string[] }
  | { k: 'showHead'; name: string; count: number }
  | { k: 'subhead'; label: string }
  | { k: 'idea'; kind?: string; title: string; who?: string; thesis: string[] }
  | { k: 'takeaways'; items: { title: string; detail: string }[] }
  | { k: 'questions'; items: string[] }
  | { k: 'themes'; items: string[] }
  | { k: 'mentions'; people: string[]; companies: string[] }
  | { k: 'quote'; title?: string; quote: string; speaker: string; role: string }
  | { k: 'moment'; ts: string; star: boolean; title: string; detail: string }
  | { k: 'qa'; q: string; a: string }
  | { k: 'sources'; rows: { episode: string; show: string; url?: string }[] }
  | { k: 'footer'; left: string; right: string }

// Parse `**bold**` into word tokens carrying a bold flag (the unit the wrapper
// lays out). Whitespace is normalised to single spaces.
export function runs(s: string): Token[] {
  const out: Token[] = []
  const push = (text: string, b: boolean) => {
    for (const w of text.split(/\s+/)) if (w) out.push({ w, b })
  }
  const re = /\*\*([^*]+)\*\*/g
  let last = 0
  let m: RegExpExecArray | null
  while ((m = re.exec(s))) {
    push(s.slice(last, m.index), false)
    push(m[1], true)
    last = re.lastIndex
  }
  push(s.slice(last), false)
  return out
}

function ideaBlock(i: WeeklyIdea | Idea): Extract<Block, { k: 'idea' }> {
  return {
    k: 'idea',
    kind: i.kind ? KIND_LABEL[i.kind] : undefined,
    title: i.idea,
    who: i.proponent && i.proponent !== '—' ? i.proponent : undefined,
    thesis: i.thesis ?? [],
  }
}

const FOOTER_LEFT = 'Generated by Munshot · AI podcast intelligence'

export function weeklyBlocks(weekly: WeeklySummary, episodeById: ById<Episode>, podcastById: ById<Podcast>): Block[] {
  const b: Block[] = []
  const eps = (n: number) => `${n} episode${n === 1 ? '' : 's'}`
  b.push({
    k: 'cover',
    eyebrow: 'AI Podcast Intelligence',
    kicker: 'Weekly Intelligence',
    title: 'Weekly Summary',
    dateRange: weekly.rangeLabel,
    chips: [eps(weekly.episodeCount), `${weekly.readMinutes} min read`],
    footerLeft: FOOTER_LEFT,
  })

  if (weekly.overview.length) {
    b.push({ k: 'section', num: '01', title: 'This Week in Summary' })
    b.push({ k: 'lead', paras: weekly.overview })
  }

  const shows = weekly.shows ?? []
  if (shows.length) {
    b.push({ k: 'section', num: '02', title: 'By Show' })
    for (const s of shows) {
      b.push({ k: 'showHead', name: s.show, count: s.episodeCount })
      if (s.ideas.length) {
        b.push({ k: 'subhead', label: 'Ideas Pitched' })
        for (const i of s.ideas) b.push(ideaBlock(i))
      }
      if (s.takeaways.length) {
        b.push({ k: 'subhead', label: 'Key Takeaways' })
        b.push({ k: 'takeaways', items: s.takeaways })
      }
      if (s.questions.length) {
        b.push({ k: 'subhead', label: 'Questions' })
        b.push({ k: 'questions', items: s.questions })
      }
    }
  }

  if (weekly.topThemes.length) {
    b.push({ k: 'section', num: '03', title: 'Top Themes' })
    b.push({ k: 'themes', items: weekly.topThemes.map((t) => t.label) })
  }

  if (weekly.mentions.people.length || weekly.mentions.companies.length) {
    b.push({ k: 'section', num: '04', title: 'Mentions' })
    b.push({ k: 'mentions', people: weekly.mentions.people, companies: weekly.mentions.companies })
  }

  if (weekly.interesting.quote) {
    b.push({ k: 'section', num: '05', title: 'What Was Actually Interesting' })
    b.push({
      k: 'quote',
      title: weekly.interesting.title,
      quote: weekly.interesting.quote,
      speaker: weekly.interesting.speaker,
      role: weekly.interesting.role,
    })
  }

  const rows = weekly.sourceEpisodeIds
    .map(episodeById)
    .filter((e): e is Episode => Boolean(e))
    .map((e) => {
      const podcast = podcastById(e.podcastId)
      return { episode: e.title, show: podcast?.title ?? '', url: episodeSourceUrl(e, podcast) }
    })
  if (rows.length) {
    b.push({ k: 'section', num: '06', title: 'Source Episodes' })
    b.push({ k: 'sources', rows })
  }

  b.push({ k: 'footer', left: FOOTER_LEFT, right: weekly.rangeLabel })
  return b
}

export function episodeBlocks(episode: Episode, podcast?: Podcast): Block[] {
  const s = episode.summary
  const b: Block[] = []
  b.push({
    k: 'cover',
    eyebrow: podcast ? `${podcast.title} · ${podcast.author}` : 'Episode Intelligence',
    kicker: 'Episode Intelligence',
    title: episode.title,
    dateRange: longDate(episode.publishedAt),
    chips: [formatDuration(episode.durationSec), ...(s ? [`${s.highlights.length} highlights`, `${s.qa.length} questions`] : [])],
    footerLeft: FOOTER_LEFT,
  })

  if (s?.synthesis.length) {
    b.push({ k: 'section', num: '01', title: 'AI Summary' })
    b.push({ k: 'lead', paras: s.synthesis })
  }
  if (s?.ideas?.length) {
    b.push({ k: 'section', num: '02', title: 'Ideas Pitched' })
    for (const i of s.ideas) b.push(ideaBlock(i))
  }
  if (s?.highlights.length) {
    b.push({ k: 'section', num: '03', title: 'Highlights' })
    for (const h of s.highlights) b.push({ k: 'moment', ts: h.timestamp, star: !!h.key, title: h.title, detail: h.detail })
  }
  if (s?.qa.length) {
    b.push({ k: 'section', num: '04', title: 'Q&A' })
    for (const item of s.qa) b.push({ k: 'qa', q: item.q, a: item.a })
  }
  b.push({ k: 'footer', left: FOOTER_LEFT, right: longDate(episode.publishedAt) })
  return b
}

// ── The painter: cursor + pagination + drawing ───────────────────────────────
type Fam = 'times' | 'helvetica' | 'courier'
interface RichOpts {
  sz: number
  lh: number
  fam: Fam
  color: RGB
  boldColor: RGB
  italic?: boolean
  indent?: number // left indent applied to the first `indentLines` lines (e.g. to clear a drop cap or a leading chip)
  indentLines?: number // how many leading lines the indent covers (default 1)
  underline?: RGB // underline every drawn line in this colour (link affordance)
  noBreak?: boolean // caller has reserved the height; don't page-break mid-block
}

export class Painter {
  readonly d: JsPdf
  private readonly logo?: string
  y = M.t

  constructor(doc: JsPdf, logo?: string) {
    this.d = doc
    this.logo = logo
  }

  private font(fam: Fam, style: string) {
    this.d.setFont(fam, style)
  }
  private color(c: RGB) {
    this.d.setTextColor(c[0], c[1], c[2])
  }
  private fill(c: RGB) {
    this.d.setFillColor(c[0], c[1], c[2])
  }
  private stroke(c: RGB, w = 0.5) {
    this.d.setDrawColor(c[0], c[1], c[2])
    this.d.setLineWidth(w)
  }
  private at(s: string, x: number, y = this.y) {
    this.d.text(s, x, y, { baseline: 'top' })
  }
  private ensure(h: number) {
    if (this.y + h > A4.h - M.b) {
      this.d.addPage()
      this.y = M.t
    }
  }
  private diamond(cx: number, cy: number, r: number) {
    this.d.triangle(cx - r, cy, cx, cy - r, cx + r, cy, 'F')
    this.d.triangle(cx - r, cy, cx, cy + r, cx + r, cy, 'F')
  }

  // Lay out `**bold**`-aware tokens with word wrap. When draw=false, measures
  // only (returns the line count); when draw=true, paints and advances y.
  private rich(tokens: Token[], x: number, maxW: number, o: RichOpts, draw: boolean): number {
    const style = (b: boolean) => (o.italic ? (b ? 'bolditalic' : 'italic') : b ? 'bold' : 'normal')
    const indent = o.indent ?? 0
    const indentLines = indent ? o.indentLines ?? 1 : 0
    const indentOf = (li: number) => (li < indentLines ? indent : 0)
    this.font(o.fam, 'normal')
    this.d.setFontSize(o.sz)
    const spaceW = this.d.getTextWidth(' ')

    // Wrap, with the available width narrowed on the indented leading lines.
    const lines: (Token & { ww: number })[][] = [[]]
    let cx = indentOf(0)
    for (const t of tokens) {
      this.font(o.fam, style(t.b))
      this.d.setFontSize(o.sz)
      const ww = this.d.getTextWidth(t.w)
      let cur = lines[lines.length - 1]
      if (cur.length && cx + spaceW + ww > maxW) {
        lines.push([])
        cur = lines[lines.length - 1]
        cx = indentOf(lines.length - 1)
      }
      if (cur.length) cx += spaceW
      cur.push({ ...t, ww })
      cx += ww
    }

    if (!draw) return lines.length
    for (let li = 0; li < lines.length; li++) {
      if (!o.noBreak) this.ensure(o.lh)
      const startX = x + indentOf(li)
      let lx = startX
      let first = true
      for (const t of lines[li]) {
        if (!first) lx += spaceW
        this.font(o.fam, style(t.b))
        this.d.setFontSize(o.sz)
        this.color(t.c ?? (t.b ? o.boldColor : o.color))
        this.at(t.w, lx)
        lx += t.ww
        first = false
      }
      if (o.underline && !first) {
        this.stroke(o.underline, 0.4)
        this.d.line(startX, this.y + o.sz * 0.92, lx, this.y + o.sz * 0.92)
      }
      this.y += o.lh
    }
    return lines.length
  }

  // ── cover (full-bleed, its own page) ──
  cover(b: Extract<Block, { k: 'cover' }>) {
    const bg = makeCoverBg()
    if (bg) this.d.addImage(bg, 'JPEG', 0, 0, A4.w, A4.h)
    else {
      this.fill(C.ink)
      this.d.rect(0, 0, A4.w, A4.h, 'F')
    }

    const fi = 31 // frame inset
    this.stroke([150, 121, 52], 0.8)
    this.d.rect(fi, fi, A4.w - 2 * fi, A4.h - 2 * fi)

    const inX = fi + 30
    const inR = A4.w - fi - 30
    let cy = fi + 30
    if (this.logo) this.d.addImage(this.logo, 'PNG', inX, cy - 2, 24, 24)
    this.font('times', 'bold')
    this.d.setFontSize(15)
    this.color(C.coverBrand)
    this.at('Munshot', inX + (this.logo ? 32 : 0), cy + 4)
    this.font('helvetica', 'bold')
    this.d.setFontSize(8)
    this.color(C.goldPale)
    this.d.setCharSpace(1.6)
    const kick = b.kicker.toUpperCase()
    this.at(kick, inR - this.d.getTextWidth(kick), cy + 7)
    this.d.setCharSpace(0)

    cy += 40
    this.stroke([150, 121, 52], 0.8)
    this.d.line(inX, cy, inR, cy)

    // hero
    const heroTop = A4.h * 0.3
    let ty = heroTop
    if (this.logo) {
      const ls = 118
      this.d.addImage(this.logo, 'PNG', (A4.w - ls) / 2, heroTop, ls, ls)
      ty = heroTop + ls + 22
    }
    if (b.eyebrow) {
      this.font('helvetica', 'bold')
      this.d.setFontSize(8.5)
      this.color(C.goldB)
      this.d.setCharSpace(2.2)
      const e = b.eyebrow.toUpperCase()
      this.at(e, (A4.w - this.d.getTextWidth(e)) / 2, ty)
      this.d.setCharSpace(0)
      ty += 20
    }
    // title — size shrinks for long episode titles
    const tsize = b.title.length > 60 ? 26 : b.title.length > 30 ? 34 : 50
    this.font('times', 'bold')
    this.d.setFontSize(tsize)
    this.color(C.coverTitle)
    const tlines = this.d.splitTextToSize(b.title, A4.w - 2 * (fi + 22)) as string[]
    for (const ln of tlines) {
      this.at(ln, (A4.w - this.d.getTextWidth(ln)) / 2, ty)
      ty += tsize * 1.04
    }
    ty += 8
    if (b.dateRange) {
      this.font('times', 'italic')
      this.d.setFontSize(17)
      this.color(C.goldPale)
      this.at(b.dateRange, (A4.w - this.d.getTextWidth(b.dateRange)) / 2, ty)
      ty += 26
    }
    if (b.chips.length) {
      this.font('courier', 'normal')
      this.d.setFontSize(7.6)
      this.d.setCharSpace(1)
      const pad = 11
      const gap = 10
      const ch = 17
      const labels = b.chips.map((c) => c.toUpperCase())
      const widths = labels.map((l) => this.d.getTextWidth(l) + pad * 2)
      const total = widths.reduce((a, w) => a + w, 0) + gap * (labels.length - 1)
      let cx2 = (A4.w - total) / 2
      this.stroke([150, 121, 52], 0.6)
      for (let i = 0; i < labels.length; i++) {
        this.d.roundedRect(cx2, ty, widths[i], ch, 8, 8, 'S')
        this.color([205, 215, 230])
        this.at(labels[i], cx2 + pad, ty + 5)
        cx2 += widths[i] + gap
      }
      this.d.setCharSpace(0)
    }

    // footer
    const by = A4.h - fi - 38
    this.stroke([150, 121, 52], 0.8)
    this.d.line(inX, by, inR, by)
    this.font('helvetica', 'normal')
    this.d.setFontSize(8)
    this.color(C.coverFoot)
    this.at(stripMd(b.footerLeft), inX, by + 10)
    if (b.dateRange) {
      this.font('courier', 'normal')
      this.d.setFontSize(7.4)
      this.color(C.goldPale)
      this.d.setCharSpace(1.2)
      const r = b.dateRange.toUpperCase()
      this.at(r, inR - this.d.getTextWidth(r), by + 10)
      this.d.setCharSpace(0)
    }
  }

  sectionHead(num: string, title: string) {
    this.ensure(34)
    this.y += 6
    this.font('times', 'bold')
    this.d.setFontSize(23)
    this.color(C.gold)
    this.at(num, M.l, this.y)
    const nw = this.d.getTextWidth(num)
    this.font('times', 'bold')
    this.d.setFontSize(15.5)
    this.color(C.navy)
    this.at(title, M.l + nw + 12, this.y + 7)
    const tw = this.d.getTextWidth(title)
    const rx = M.l + nw + 12 + tw + 12
    this.stroke(C.gold, 0.8)
    if (rx < A4.w - M.r) this.d.line(rx, this.y + 16, A4.w - M.r, this.y + 16)
    this.y += 30
  }

  lead(paras: string[]) {
    const padX = 16
    const padT = 13
    const padB = 11
    const lh = 15
    const sz = 10.2
    const capSz = 26
    const capLines = 2 // a 26pt initial descends ~2 body lines; indent both so text never slides under it
    const innerW = CW - 2 * padX
    const baseOpt = (indent = 0): RichOpts => ({ sz, lh, fam: 'helvetica', color: C.ink2, boldColor: C.gold, indent, indentLines: capLines, noBreak: true })

    // Drop cap only when the first paragraph is genuinely multi-line — otherwise a
    // tall initial would dangle past the paragraph (and into the next block).
    const capChar = (paras[0] || '').charAt(0)
    let capW = 0
    if (capChar) {
      this.font('times', 'bold')
      this.d.setFontSize(capSz)
      capW = this.d.getTextWidth(capChar)
    }
    const useCap = !!capChar && this.rich(runs(paras[0] || ''), M.l + padX, innerW, baseOpt(), false) >= capLines

    // Per-paragraph token + indent (first paragraph drops its initial when useCap).
    const items = paras.map((p, i) => (i === 0 && useCap ? { tokens: runs(p.slice(1)), opt: baseOpt(capW + 8) } : { tokens: runs(p), opt: baseOpt() }))

    let total = padT
    items.forEach((it, i) => {
      if (i > 0) total += 8
      total += this.rich(it.tokens, M.l + padX, innerW, it.opt, false) * lh
    })
    total += padB

    this.ensure(total)
    const top = this.y
    this.fill(C.goldTint)
    this.d.rect(M.l, top, CW, total, 'F')
    this.fill(C.gold)
    this.d.rect(M.l, top, 3, total, 'F')

    this.y = top + padT
    if (useCap) {
      this.font('times', 'bold')
      this.d.setFontSize(capSz)
      this.color(C.gold)
      this.at(capChar, M.l + padX, this.y - 2)
    }
    items.forEach((it, i) => {
      if (i > 0) this.y += 8
      this.rich(it.tokens, M.l + padX, innerW, it.opt, true)
    })
    this.y = top + total + 12
  }

  showHead(name: string, count: number) {
    this.ensure(26)
    this.y += 6
    this.font('times', 'bold')
    this.d.setFontSize(13.5)
    this.color(C.navy)
    this.at(name, M.l, this.y)
    const label = `${count} EPISODE${count === 1 ? '' : 'S'}`
    this.font('helvetica', 'bold')
    this.d.setFontSize(7.2)
    this.d.setCharSpace(0.6)
    const w = this.d.getTextWidth(label) + 16
    this.fill(C.goldTint)
    this.stroke([150, 121, 52], 0.5)
    this.d.roundedRect(M.l + CW - w, this.y - 1, w, 13, 6, 6, 'FD')
    this.color(C.gold)
    this.at(label, M.l + CW - w + 8, this.y + 2.5)
    this.d.setCharSpace(0)
    this.y += 18
    this.stroke(C.line2, 0.5)
    this.d.line(M.l, this.y, M.l + CW, this.y)
    this.y += 9
  }

  subhead(label: string) {
    this.ensure(20)
    this.y += 4
    this.fill(C.gold)
    this.d.rect(M.l, this.y + 3, 12, 2, 'F')
    this.font('helvetica', 'bold')
    this.d.setFontSize(7.8)
    this.color(C.gold)
    this.d.setCharSpace(1.4)
    this.at(label.toUpperCase(), M.l + 18, this.y)
    this.d.setCharSpace(0)
    this.y += 15
  }

  idea(b: Extract<Block, { k: 'idea' }>) {
    const padX = 12
    const padV = 9
    const innerW = CW - 2 * padX
    let kindW = 0
    if (b.kind) {
      this.font('helvetica', 'bold')
      this.d.setFontSize(6.8)
      kindW = this.d.getTextWidth(b.kind.toUpperCase()) + 12 + 7
    }
    const titleOpt: RichOpts = { sz: 11.4, lh: 14, fam: 'times', color: C.navy, boldColor: C.navy, indent: kindW, noBreak: true }
    const thOpt: RichOpts = { sz: 9.2, lh: 12.5, fam: 'helvetica', color: C.body, boldColor: C.gold, noBreak: true }

    let h = padV + this.rich(runs(b.title), M.l + padX, innerW, titleOpt, false) * 14
    if (b.who) h += 5 + 16
    if (b.thesis.length) {
      h += 4
      for (const t of b.thesis) h += this.rich(runs(t), M.l + padX + 14, innerW - 14, thOpt, false) * 12.5 + 2
    }
    h += padV

    this.ensure(h)
    const top = this.y
    this.fill(C.panel)
    this.d.rect(M.l, top, CW, h, 'F')
    this.fill(C.gold)
    this.d.rect(M.l, top, 3, h, 'F')
    this.stroke(C.line, 0.5)
    this.d.rect(M.l, top, CW, h)

    this.y = top + padV
    if (b.kind) {
      const kl = b.kind.toUpperCase()
      this.font('helvetica', 'bold')
      this.d.setFontSize(6.8)
      const w = this.d.getTextWidth(kl) + 12
      this.stroke([150, 121, 52], 0.5)
      this.d.roundedRect(M.l + padX, this.y, w, 11, 3, 3, 'S')
      this.color(C.gold)
      this.at(kl, M.l + padX + 6, this.y + 2.8)
    }
    this.rich(runs(b.title), M.l + padX, innerW, titleOpt, true)
    if (b.who) {
      this.y += 5
      this.font('helvetica', 'normal')
      this.d.setFontSize(7.3)
      const pre = 'Pitched by '
      const w = this.d.getTextWidth(pre + b.who) + 18
      this.fill(C.white)
      this.stroke(C.line2, 0.5)
      this.d.roundedRect(M.l + padX, this.y, w, 14, 7, 7, 'FD')
      this.color(C.slate)
      this.at(pre, M.l + padX + 9, this.y + 3.5)
      const pw = this.d.getTextWidth(pre)
      this.font('helvetica', 'bold')
      this.color(C.navy)
      this.at(b.who, M.l + padX + 9 + pw, this.y + 3.5)
      this.y += 16
    }
    if (b.thesis.length) {
      this.y += 4
      for (const t of b.thesis) {
        this.fill(C.gold)
        this.diamond(M.l + padX + 3, this.y + 5, 2.4)
        this.rich(runs(t), M.l + padX + 14, innerW - 14, thOpt, true)
        this.y += 2
      }
    }
    this.y = top + h + 7
  }

  takeaways(items: { title: string; detail: string }[]) {
    const lh = 14
    for (const it of items) {
      const titleWords = it.title
        .split(/\s+/)
        .filter(Boolean)
        .map((w, i, a): Token => ({ w: i === a.length - 1 ? w + '.' : w, b: true, c: C.navy }))
      const toks = titleWords.concat(runs(it.detail))
      const opt: RichOpts = { sz: 10, lh, fam: 'helvetica', color: C.body, boldColor: C.gold, noBreak: true }
      const lines = this.rich(toks, M.l + 16, CW - 16, opt, false)
      this.ensure(lines * lh + 6)
      this.fill(C.gold)
      this.d.rect(M.l + 1, this.y + 5, 4, 4, 'F')
      this.rich(toks, M.l + 16, CW - 16, opt, true)
      this.y += 6
    }
  }

  questions(items: string[]) {
    const lh = 12.5
    for (const q of items) {
      const opt: RichOpts = { sz: 9, lh, fam: 'helvetica', italic: true, color: [70, 86, 111], boldColor: C.gold, noBreak: true }
      const lines = this.rich(runs(q), M.l + 14, CW - 14, opt, false)
      this.ensure(lines * lh + 6)
      this.fill(C.goldB)
      this.d.rect(M.l, this.y + 1, 2, lines * lh - 2, 'F')
      this.rich(runs(q), M.l + 14, CW - 14, opt, true)
      this.y += 6
    }
  }

  themes(items: string[]) {
    this.font('courier', 'normal')
    this.d.setFontSize(8)
    const pad = 10
    const gap = 7
    const ch = 16
    const lh = ch + 7
    let cx = M.l
    this.ensure(ch)
    for (const raw of items) {
      const label = raw.toUpperCase()
      const w = this.d.getTextWidth(label) + pad * 2
      if (cx > M.l && cx + w > M.l + CW) {
        this.y += lh
        cx = M.l
        this.ensure(ch)
      }
      this.fill(C.goldTint)
      this.stroke([150, 121, 52], 0.5)
      this.d.roundedRect(cx, this.y, w, ch, 8, 8, 'FD')
      this.color(C.navy)
      this.at(label, cx + pad, this.y + 4.5)
      cx += w + gap
    }
    this.y += ch + 8
  }

  mentions(people: string[], companies: string[]) {
    const groups: [string, string[]][] = [
      ['People', people],
      ['Companies', companies],
    ]
    for (const [label, items] of groups) {
      if (!items.length) continue
      this.ensure(24)
      this.y += 2
      this.font('helvetica', 'bold')
      this.d.setFontSize(8)
      this.color(C.navy)
      this.d.setCharSpace(1.4)
      this.at(label.toUpperCase(), M.l, this.y)
      this.d.setCharSpace(0)
      this.y += 11
      this.stroke(C.gold, 1.2)
      this.d.line(M.l, this.y, M.l + CW, this.y)
      this.y += 8
      // chips
      this.font('helvetica', 'bold')
      this.d.setFontSize(8)
      const pad = 10
      const gap = 5
      const ch = 15
      const lh = ch + 5
      let cx = M.l
      this.ensure(ch)
      for (const it of items) {
        const w = this.d.getTextWidth(it) + pad * 2
        if (cx > M.l && cx + w > M.l + CW) {
          this.y += lh
          cx = M.l
          this.ensure(ch)
        }
        this.fill(C.panel2)
        this.stroke(C.line2, 0.5)
        this.d.roundedRect(cx, this.y, w, ch, 7, 7, 'FD')
        this.color(C.navy)
        this.at(it, cx + pad, this.y + 3.5)
        cx += w + gap
      }
      this.y += ch + 8
    }
  }

  quote(b: Extract<Block, { k: 'quote' }>) {
    const padX = 22
    const padV = 18
    const innerW = CW - 2 * padX
    const titleOpt: RichOpts = { sz: 15, lh: 18, fam: 'times', color: C.goldPale, boldColor: C.goldPale, noBreak: true }
    const qOpt: RichOpts = { sz: 12.4, lh: 17, fam: 'times', italic: true, color: [221, 230, 242], boldColor: C.goldPale, noBreak: true }

    let h = padV
    if (b.title) h += this.rich(runs(b.title), M.l + padX, innerW, titleOpt, false) * 18 + 8
    h += this.rich(runs(b.quote), M.l + padX, innerW, qOpt, false) * 17
    h += 14 + 12 + padV

    this.ensure(h)
    const top = this.y
    this.fill(C.quoteBg)
    this.d.roundedRect(M.l, top, CW, h, 12, 12, 'F')
    this.stroke([150, 121, 52], 0.6)
    this.d.roundedRect(M.l, top, CW, h, 12, 12, 'S')
    // oversized quote mark, faint gold
    this.font('times', 'bold')
    this.d.setFontSize(58)
    this.color(C.gold)
    this.d.setGState(this.d.GState({ opacity: 0.22 }))
    this.at('“', M.l + 10, top - 8)
    this.d.setGState(this.d.GState({ opacity: 1 }))

    this.y = top + padV
    if (b.title) {
      this.rich(runs(b.title), M.l + padX, innerW, titleOpt, true)
      this.y += 8
    }
    this.rich(runs(b.quote), M.l + padX, innerW, qOpt, true)
    this.y += 12
    this.fill(C.goldB)
    this.diamond(M.l + padX + 3, this.y + 5, 2.4)
    this.font('helvetica', 'bold')
    this.d.setFontSize(8.4)
    this.color(C.goldB)
    this.at(b.speaker, M.l + padX + 12, this.y + 1.5)
    const sw = this.d.getTextWidth(b.speaker)
    this.font('helvetica', 'normal')
    this.d.setFontSize(8)
    this.color([159, 177, 200])
    this.at('  ' + b.role, M.l + padX + 12 + sw, this.y + 1.5)
    this.y = top + h + 12
  }

  moment(b: Extract<Block, { k: 'moment' }>) {
    const padX = 12
    const padV = 9
    const innerW = CW - 2 * padX
    this.font('courier', 'normal')
    this.d.setFontSize(7.4)
    const tsW = this.d.getTextWidth(b.ts) + 12
    let indent = tsW + 8
    if (b.star) indent += 12
    const titleOpt: RichOpts = { sz: 11.2, lh: 14, fam: 'times', color: C.navy, boldColor: C.navy, indent, noBreak: true }
    const whyOpt: RichOpts = { sz: 9.2, lh: 13, fam: 'helvetica', color: C.body, boldColor: C.gold, noBreak: true }

    let h = padV + this.rich(runs(b.title), M.l + padX, innerW, titleOpt, false) * 14
    h += 4 + this.rich(runs(b.detail), M.l + padX, innerW, whyOpt, false) * 13 + padV

    this.ensure(h)
    const top = this.y
    this.fill(C.panel)
    this.d.rect(M.l, top, CW, h, 'F')
    this.fill(C.gold)
    this.d.rect(M.l, top, 3, h, 'F')
    this.stroke(C.line, 0.5)
    this.d.rect(M.l, top, CW, h)

    this.y = top + padV
    this.fill(C.goldTint)
    this.stroke([150, 121, 52], 0.5)
    this.d.roundedRect(M.l + padX, this.y, tsW, 12, 4, 4, 'FD')
    this.font('courier', 'normal')
    this.d.setFontSize(7.4)
    this.color(C.gold)
    this.at(b.ts, M.l + padX + 6, this.y + 2.8)
    if (b.star) {
      this.fill(C.gold)
      this.diamond(M.l + padX + tsW + 8, this.y + 6, 3)
    }
    this.rich(runs(b.title), M.l + padX, innerW, titleOpt, true)
    this.y += 4
    this.rich(runs(b.detail), M.l + padX, innerW, whyOpt, true)
    this.y = top + h + 7
  }

  qa(b: Extract<Block, { k: 'qa' }>) {
    const qbW = 16
    const qOpt: RichOpts = { sz: 11.2, lh: 14, fam: 'times', color: C.navy, boldColor: C.navy, noBreak: true }
    const qLines = this.rich(runs(b.q), M.l + qbW + 8, CW - qbW - 8, qOpt, false)
    this.ensure(qLines * 14 + 20)
    this.y += 2
    this.fill(C.gold)
    this.d.roundedRect(M.l, this.y, qbW, 12, 2, 2, 'F')
    this.font('helvetica', 'bold')
    this.d.setFontSize(7.2)
    this.color(C.white)
    this.at('Q', M.l + (qbW - this.d.getTextWidth('Q')) / 2, this.y + 2.8)
    this.rich(runs(b.q), M.l + qbW + 8, CW - qbW - 8, qOpt, true)
    this.y += 4
    // answer is breakable (can run long)
    this.rich(runs(b.a), M.l, CW, { sz: 9.4, lh: 13.5, fam: 'helvetica', color: C.body, boldColor: C.gold }, true)
    this.y += 9
    this.stroke(C.line, 0.5)
    this.d.line(M.l, this.y, M.l + CW, this.y)
    this.y += 9
  }

  sources(rows: { episode: string; show: string; url?: string }[]) {
    const palette: RGB[] = [C.navy, C.gold, C.slate]
    const colorMap = new Map<string, RGB>()
    let ci = 0
    const tagColor = (show: string): RGB => {
      let c = colorMap.get(show)
      if (!c) {
        c = palette[ci++ % palette.length]
        colorMap.set(show, c)
      }
      return c
    }
    const inset = 9 // header text + row text + tag all align to this inset from the table edges
    const left = M.l + inset
    const right = M.l + CW - inset
    const header = () => {
      this.font('helvetica', 'bold')
      this.d.setFontSize(6.9)
      this.color(C.gold)
      this.d.setCharSpace(1.4)
      this.at('EPISODE', left, this.y + 4)
      const sh = 'SHOW'
      this.at(sh, right - this.d.getTextWidth(sh), this.y + 4)
      this.d.setCharSpace(0)
      this.y += 14
      this.stroke(C.gold, 1.4)
      this.d.line(M.l, this.y, M.l + CW, this.y)
    }
    this.ensure(40)
    header()
    let zebra = false
    const tagW = (show: string) => {
      if (!show) return 0
      this.font('helvetica', 'bold')
      this.d.setFontSize(6.9)
      return this.d.getTextWidth(show.toUpperCase()) + 16
    }
    for (const row of rows) {
      const tw = tagW(row.show)
      const epW = CW - 2 * inset - tw - 14 // episode text never runs under the tag
      const epOpt: RichOpts = { sz: 9.1, lh: 12, fam: 'helvetica', color: C.navy, boldColor: C.navy, underline: row.url ? C.navy : undefined, noBreak: true }
      const lines = this.rich(runs(row.episode), left, epW, epOpt, false)
      const rh = Math.max(lines * 12 + 11, 26)
      if (this.y + rh > A4.h - M.b) {
        this.d.addPage()
        this.y = M.t
        header()
      }
      const top = this.y
      if (zebra) {
        this.fill(C.zebra)
        this.d.rect(M.l, top, CW, rh, 'F')
      }
      this.y = top + 6
      this.rich(runs(row.episode), left, epW, epOpt, true)
      if (row.show) {
        const t = row.show.toUpperCase()
        this.font('helvetica', 'bold')
        this.d.setFontSize(6.9)
        const yy = top + (rh - 13) / 2
        this.fill(tagColor(row.show))
        this.d.roundedRect(right - tw, yy, tw, 13, 3, 3, 'F')
        this.color(C.white)
        this.d.setCharSpace(0.4)
        this.at(t, right - tw + 8, yy + 3)
        this.d.setCharSpace(0)
      }
      // Whole row is a hyperlink to the episode at its source (Apple / YouTube / RSS).
      if (row.url) this.d.link(M.l, top, CW, rh, { url: row.url })
      this.y = top + rh
      this.stroke(C.line, 0.5)
      this.d.line(M.l, this.y, M.l + CW, this.y)
      zebra = !zebra
    }
    this.y += 4
  }

  footer(left: string, right: string) {
    this.ensure(32)
    this.y += 12
    this.stroke([216, 193, 135], 0.5)
    this.d.line(M.l, this.y, M.l + CW, this.y)
    this.y += 8
    this.font('helvetica', 'normal')
    this.d.setFontSize(7.6)
    this.color([136, 147, 162])
    this.at(stripMd(left), M.l, this.y)
    this.color(C.gold)
    this.d.setCharSpace(1)
    const r = right.toUpperCase()
    this.at(r, M.l + CW - this.d.getTextWidth(r), this.y)
    this.d.setCharSpace(0)
  }
}

function stripMd(s: string): string {
  return s.replace(/\*\*/g, '')
}

// Paint the cover's layered gradients to a canvas and return a JPEG data URI, so
// the cover keeps the exact dark navy + gold-glow look (jsPDF has no gradients).
// Returns null when there's no DOM (e.g. tests) — the caller falls back to a
// solid navy fill.
function makeCoverBg(): string | null {
  if (typeof document === 'undefined') return null
  try {
    const sc = 2
    const W = Math.round(A4.w * sc)
    const H = Math.round(A4.h * sc)
    const canvas = document.createElement('canvas')
    canvas.width = W
    canvas.height = H
    const x = canvas.getContext('2d')
    if (!x) return null
    const lin = x.createLinearGradient(0, 0, W * 0.4, H)
    lin.addColorStop(0, '#0a1322')
    lin.addColorStop(0.46, '#14233c')
    lin.addColorStop(1, '#0b182c')
    x.fillStyle = lin
    x.fillRect(0, 0, W, H)
    const navy = x.createRadialGradient(W * 0.8, H * 1.05, 0, W * 0.8, H * 1.05, Math.max(W, H) * 0.9)
    navy.addColorStop(0, 'rgba(30,55,95,0.55)')
    navy.addColorStop(0.55, 'rgba(10,18,34,0)')
    x.fillStyle = navy
    x.fillRect(0, 0, W, H)
    const wash = x.createRadialGradient(W * 0.5, H * 0.3, 0, W * 0.5, H * 0.3, Math.max(W, H) * 0.5)
    wash.addColorStop(0, 'rgba(184,144,47,0.16)')
    wash.addColorStop(0.42, 'rgba(184,144,47,0)')
    x.fillStyle = wash
    x.fillRect(0, 0, W, H)
    const glow = x.createRadialGradient(W * 0.5, H * 0.44, 0, W * 0.5, H * 0.44, W * 0.34)
    glow.addColorStop(0, 'rgba(184,144,47,0.3)')
    glow.addColorStop(0.68, 'rgba(184,144,47,0)')
    x.fillStyle = glow
    x.fillRect(0, 0, W, H)
    return canvas.toDataURL('image/jpeg', 0.92)
  } catch {
    return null
  }
}

// ── public render + download ─────────────────────────────────────────────────
export function renderBlocks(p: Painter, blocks: Block[]): void {
  for (const b of blocks) {
    switch (b.k) {
      case 'cover':
        p.cover(b)
        p.d.addPage()
        p.y = M.t
        break
      case 'section':
        p.sectionHead(b.num, b.title)
        break
      case 'lead':
        p.lead(b.paras)
        break
      case 'showHead':
        p.showHead(b.name, b.count)
        break
      case 'subhead':
        p.subhead(b.label)
        break
      case 'idea':
        p.idea(b)
        break
      case 'takeaways':
        p.takeaways(b.items)
        break
      case 'questions':
        p.questions(b.items)
        break
      case 'themes':
        p.themes(b.items)
        break
      case 'mentions':
        p.mentions(b.people, b.companies)
        break
      case 'quote':
        p.quote(b)
        break
      case 'moment':
        p.moment(b)
        break
      case 'qa':
        p.qa(b)
        break
      case 'sources':
        p.sources(b.rows)
        break
      case 'footer':
        p.footer(b.left, b.right)
        break
    }
  }
}

async function buildAndSave(blocks: Block[], baseName: string): Promise<void> {
  const [{ jsPDF }, { MUNSHOT_LOGO }] = await Promise.all([import('jspdf'), import('./brandLogo')])
  const doc = new jsPDF({ unit: 'pt', format: 'a4', compress: true })
  doc.setProperties({ title: baseName })
  renderBlocks(new Painter(doc, MUNSHOT_LOGO), blocks)
  const blob = doc.output('blob')
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${sanitizeFilename(baseName)}.pdf`
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 10_000)
}

export function downloadWeeklyPdf(weekly: WeeklySummary, episodeById: ById<Episode>, podcastById: ById<Podcast>): Promise<void> {
  return buildAndSave(weeklyBlocks(weekly, episodeById, podcastById), `Munshot Weekly — ${weekly.rangeLabel}`)
}

export function downloadSummaryPdf(episode: Episode, podcast?: Podcast): Promise<void> {
  return buildAndSave(episodeBlocks(episode, podcast), `${episode.title} — Munshot Summary`)
}
