/** @type {import('tailwindcss').Config} */
// SignalCast design tokens — "Signal over Noise".
// Paper-like canvas, white cards, a single blue accent, Inter type scale.
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f9f9f9',
        'on-background': '#1a1c1c',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#414755',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        outline: '#717786',
        'outline-variant': '#c1c6d7',
        'surface-tint': '#005bc1',
        primary: '#0058bc',
        'on-primary': '#ffffff',
        'primary-container': '#0070eb',
        'on-primary-container': '#fefcff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'inverse-primary': '#adc6ff',
        secondary: '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2dfde',
        'on-secondary-container': '#636262',
        tertiary: '#5b5c60',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#747479',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        success: '#1c7d52',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        metadata: ['13px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0' }],
        'headline-mobile': ['22px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-sm': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '32px',
        xl: '48px',
        gutter: '24px',
      },
      maxWidth: {
        container: '1120px',
        reading: '800px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 4px 12px rgba(0,0,0,0.03)',
        player: '0 8px 30px rgba(0,0,0,0.08)',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.4s ease-out both',
      },
    },
  },
  plugins: [],
}
